### ISSUE TITLE
Novel Poses Process

### ISSUE THREAD

**Issue by zhao-yiqun** [taconite/IntrinsicAvatar#4]
Hi

Thanks for your amazing project! I want to render the novel poses beyond aist_demo.npz like other actions such as kick, punch(from AMASS dataset) etc as in your project page [IntrinsicAvatar](https://neuralbodies.github.io/IntrinsicAvatar/). I wonder how should I process the poses from AMASS to make it suitable for the dataloader you provided [datasets/animation.py](https://github.com/taconite/IntrinsicAvatar/blob/main/datasets/animation.py).  Could you please share your pose processing scripts?

Thanks in advance.

Bests

**Comment by taconite** [comment]
Hi, Yiqun

Thanks for your interest in our work :)

Actually, the kick and punch poses in our video are from the [CAPE dataset](https://cape.is.tue.mpg.de/index.html). I've updated my preprocessing script for CAPE poses to the repo, though in order to work with AMASS you may need to remove hand poses of AMASS since it uses SMPL+H model.

Hope this helps.

Best

**Comment by zhao-yiqun** [comment]
Thanks fot the sharing!
